rescue_soul/rescue_soul/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.views.generic.base import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('soul.urls'))
]

rescue_soul/soul/urls.py
from django.urls import path,include
from . import views
app_name='soul'

urlpatterns=[
    path('home/',views.homepage,name="homepage"),
    #path('try/',views.tr,name="try"),
    path('login/',views.check_login,name='login'),
    #path('log/',views.log,name='log'),
    path('register/',views.register,name='register'),
    path('forgot/', views.forgot, name='forgot'),
    path('forgotPage/', views.forgotPage, name='forgotPage'),
    path('ngoConsultation/',views.ngoConsultation, name='ngoConsultation'),
    path('vetConsultation/',views.vetConsultation, name='vetConsultation'),
    path('login_render/',views.login_render, name='login_render'),
    path('contacts/',views.contacts, name='contacts'),
    path('donate/',views.donate,name='donate'),
    path('success/',views.success,name='success'),
    path('petfinder/',views.petfinder,name='petfinder'),
    path('app/',views.app,name='app'),
    path('share/',views.share,name='share'),
    path('petfinderform/',views.petfinderform,name='petfinderform'),
    path('logout/',views.logout, name='logout'),
    path('changePassword/',views.changePassword, name='changePassword'),
    path('update/',views.update, name='update'),
    path('check_login/',views.check_login, name='check_login'),
]

rescue_soul/soul/models.py
from django.db import models

# Create your models here.


class Register(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.name+" "+self.email+" "+self.password

class contact(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    subject=models.CharField(max_length=150)
    message=models.CharField(max_length=250)

    def __str__(self):
        return self.name+" "+self.email+" "+self.subject+" "+self.message

class donatethings(models.Model):
    firstname=models.CharField(max_length=100)
    lastname=models.CharField(max_length=100)
    address=models.CharField(max_length=250)
    country=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    city=models.CharField(max_length=100)
    email=models.EmailField()
    phone=models.CharField(max_length=20)
    message=models.CharField(max_length=250)

    def __str__(self):
        return self.firstname+" "+self.lastname+" "+self.address+" "+self.country
        +" "+self.state+" "+self.city+" "+self.phonw+" "+self.message

class sharethoughts(models.Model):
    sharetext=models.CharField(max_length=250)
    sharefile=models.FileField(upload_to='share_experience')

    def __str__(self):
        return self.sharetext+" "+self.sharefile

class pet(models.Model):
    firstname=models.CharField(max_length=100)
    lastname=models.CharField(max_length=100)
    address=models.CharField(max_length=250)
    country=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    city=models.CharField(max_length=100)
    email=models.EmailField()
    phone=models.CharField(max_length=20)
    message=models.CharField(max_length=250)

    def __str__(self):
        return self.firstname+" "+self.lastname+" "+self.address+" "+self.country
        +" "+self.state+" "+self.city+" "+self.phone+" "+self.message

rescue_soul/soul/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_control
from .models import Register,contact,donatethings,sharethoughts,pet
from django.http import HttpResponse
from django.views.generic import *
from soul.models import *
from django.shortcuts import render,redirect,get_object_or_404
from django.core.mail import send_mail,BadHeaderError
from django.core.validators import validate_email

# Create your views here.


def homepage(request):
    return render(request,"home.html")


def app(request):
   return render(request,"app.html")


def ngoConsultation(request):
    return render(request, "ngoConsultation.html")


def vetConsultation(request):
    return render(request, "vetConsultation.html")


def login_render(request):
    return render(request, "login_render.html")


#def log(request):
 #   return render(request,"pet_finder.html")


register_success = False
login_success = False
login_s = True
change_success = False

def donate(request):
    if request.method == 'POST':
        if request.POST.get('firstname') and request.POST.get('lastname') \
                and request.POST.get('address') and request.POST.get('country') \
                and request.POST.get('state') and request.POST.get('city') \
                and request.POST.get('email') and request.POST.get('phone') \
                and request.POST.get('message'):
            post = donatethings()
            post.firstname = request.POST.get('firstname')
            post.lastname = request.POST.get('lastname')
            post.address = request.POST.get('address')
            post.country = request.POST.get('country')

            post.state = request.POST.get('state')

            post.city = request.POST.get('city')

            post.email = request.POST.get('email')
            post.phone = request.POST.get('phone')
            post.message=request.POST.get('message')
            post.save()

            try:
                send_mail('Rescue soul',"thank you for your donation. your request has been recieved by us.our team member will soon connect to you at your given address.","gauttamdivisha96@gmail.com",[post.email])
            except BadHeaderError:
                return HttpResponse('invalid header found')
            return redirect("soul:success")


        else:
            return render(request, "fail.html")
    return render(request,"donate_things.html")

def petfinder(request):
    return render(request,"pet_finder.html")

def share(request):
    print("Share")
    saved = False
    if request.method == 'POST':
            post=sharethoughts()
            post.sharetext = request.POST.get('sharetext')
            if 'sharefile' in request.FILES:
                post.sharefile = request.FILES['sharefile']
                print(post.sharetext, post.sharefile)
            else:
                post.sharefile = 'img/bird.jpg'

            post.save()
            saved = True

            return render(request, "login_render.html", {'success':saved})
    return render(request,"login_render.html")


def petfinderform(request):
    if request.method == 'POST':
        if request.POST.get('firstname') and request.POST.get('lastname') \
                and request.POST.get('address') and request.POST.get('country') \
                and request.POST.get('state') and request.POST.get('city') \
                and request.POST.get('email') and request.POST.get('phone') \
                and request.POST.get('message'):
            post = pet()
            post.firstname = request.POST.get('firstname')
            post.lastname = request.POST.get('lastname')
            post.address = request.POST.get('address')
            post.country = request.POST.get('country')

            post.state = request.POST.get('state')

            post.city = request.POST.get('city')

            post.email = request.POST.get('email')
            post.phone = request.POST.get('phone')
            post.message=request.POST.get('message')
            post.save()

            try:
                send_mail('Rescue soul',"we are apreciating your effort "
                "to adobt a soul, we will surely connect you soon. "
                "thank you !!","gauttamdivisha96@gmail.com",[post.email])
            except BadHeaderError:
                return HttpResponse('invalid header found')
            return render(request,"adoptpet.html")


        else:
            return render(request, "f.html")
    return render(request,"adoptpet.html")


def contacts(request):
    if request.method == 'POST':
        if request.POST.get('name') and request.POST.get('email') \
                and request.POST.get('subject') and request.POST.get('message'):
            post = contact()
            post.name = request.POST.get('name')
            post.email = request.POST.get('email')
            post.subject = request.POST.get('subject')
            post.message=request.POST.get('message')
            post.save()

            return render(request, "contact.html")
        else:
            return render(request, "fail.html")
    return render(request,"contact.html")


def register(request):
    global register_success
    if request.method == 'POST':
        if request.POST.get('name') and request.POST.get('email') \
                and request.POST.get('password'):
            post = Register()
            post.name = request.POST.get('name')
            post.email = request.POST.get('email')
            post.password = request.POST.get('password')
            post.save()
            register_success = True
            return render(request, "registration.html",
                          {"register_success": register_success})
        else:
            return render(request, "fail.html")
    return render(request,"registration.html")


def update(request):
    global update_users
    u_password = request.POST.get('oldPassword')
    #print(u_password)
    try:
        print("In try")
        update_users = Register.objects.get(email=l_email, password=u_password)
        #print("pass=",update_users)

    except Exception as e:
        print("exception = ",e)
        change_success = False
        return render(request, "fail.html",
                      {"change_success": change_success})

    try:
        if update_users.password == u_password:

        #p = Register()
            new_password = request.POST.get('newPassword')
            Register.objects.all().filter(email= l_email,
            password = u_password).update(password=new_password)
            change_success = True
            return render(request, "success.html",
                          {"change_success": change_success})

    except Exception as e:
        print("2nd Exception = ", e)
        change_success = False
        return render(request, "fail.html",
                      {"change_success": change_success})


def check_login(request):
    global users, l_email, l_password
    if request.method == 'GET':
       # print("In get")
        render(request, "login.html")
    
    else:
        l_email = request.POST.get('email')
        l_password = request.POST.get('password')
        #print(l_email, l_password)
        try:
            print("in try")
            users = Register.objects.get(email=l_email, password=l_password)
            print("users in try= ", users)
        except Exception as e:
            login_success = True
            request.session['username'] = None
            print(e)
            return render(request, "login.html",
                          {"login_success": login_success})

        print(users.email, users.password)

        if users.email == l_email and users.password == l_password:
            request.session['username'] = users.name
            return render(request, "login_render.html",
                          {"username": request.session['username']})

    return render(request, "login.html")


def forgotPage(request):
    return render(request, "forgot_password.html")
def forgot(request):
    global users, f_email , f_pass
    f_email = request.POST.get('email')
    print(f_email)
    users = Register.objects.get(email=f_email)
    print(users)
    print("pass = ",users.password)
    '''if f_email == users.email:
        users=Register.objects.get(password=f_pass)
    try:
            send_mail('Rescue soul',"your password:"+users.email and users.password,"gauttamdivisha96@gmail.com", [users.email])
    except BadHeaderError:
        return HttpResponse('invalid header found')
    return redirect("soul:success")
    return HttpResponse("Hello")
    '''
    try:
        send_mail('Rescue the Soul',
                  "Your new password is "+users.password+". Please, login again and don't "
                  "forget to change your password for the security reasons. Thank You!",
                  "gauttamdivisha96@gmail.com", [users.email])
    except BadHeaderError:
        return HttpResponse('invalid header found')
    pass_success = True
    return render(request, "forgot_password.html",
                  {"pass_success": pass_success})


def success(request):
    return render(request,"success.html")


def changePassword(request):
    return render(request, "changePassword.html")

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def logout(request):
    try:
        del request.session["username"]
        request.session.flush()
    except KeyError:
        pass
    return render(request, "home.html")

rescue_soul/soul/templates/adoptpet.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
<head>
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet finder Form</title>

    <link rel="stylesheet" href={% static "css/linearicons.css" %}>
			<link rel="stylesheet" href={% static "css/font-awesome.min.css" %}>
			<link rel="stylesheet" href={% static "css/bootstrap.css" %}>
			<link rel="stylesheet" href={% static "css/magnific-popup.css" %}>
			<link rel="stylesheet" href={% static "css/nice-select.css" %}>
			<link rel="stylesheet" href={% static "css/animate.min.css" %}>
			<link rel="stylesheet" href={% static "css/owl.carousel.css" %}>
			<link rel="stylesheet" href={% static "css/main.css" %}>
			<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
			<link rel="stylesheet" href={% static "css/all.min.css" %}>
            <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css'%}">

    <link rel="stylesheet" href={% static "css/all.min.css" %}>
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "css/Login-Form-Dark.css" %}>
    <link rel="stylesheet" href={% static "css/Registration-Form-with-Photo.css" %}>


    <style>
        /* Bordered form */
form {
  border: 3px solid #f1f1f1;
}

/* Full-width inputs */
input[type=text], input[type=password],input[type=email],textarea {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

select{
    width: 20%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

/* Add a hover effect for buttons */
button:hover {
  opacity: 0.8;
}

/* Extra style for the cancel button (red) */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

/* Center the avatar image inside this container */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}

/* Avatar image */
img.avatar {
  width: 40%;
  border-radius: 50%;
}

/* Add padding to containers */
.container {
  padding: 16px;
}

/* The "Forgot password" text */
span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
    display: block;
    float: none;
  }
  .cancelbtn {
    width: 100%;
  }
}
    </style>
</head>
<body>

                    <header id="header" id="home" style="background-color: black">
			    <div class="container main-menu">
			    	<div class="row align-items-center justify-content-between d-flex">
				      <div id="logo">
				        <a href="home.html"><img src="{% static "img/rescuelogo.png" %}"
                                                 alt="" title="" /></a>

                    </div>
				      <nav id="nav-menu-container" style="font-size: small">
				        <ul class="nav-menu" style="text-decoration: none">

				          <li class="menu-active">

                              <a href="{% url 'soul:login_render' %}"
							  style="color: white; font-size: 15px">
								  <i class="fas fa-home"></i>
								  Home
							  </a>
						  </li>
				          <li><a href="{% url 'soul:donate' %}"
						  style="color: white; font-size: 15px">
							  <i class="fas fa-hands-helping"></i>
							  Donate Things
						  	</a>
						  </li>


				          <li class="menu-has-children">
							  <a href=""
							  style="color: white; font-size: 15px">
							  <i class="fas fa-notes-medical"></i>
							  Consultation
						  </a>
				            <ul>
				              <li><a href="{% url 'soul:ngoConsultation' %}">NGO Consultation</a></li>
				              <li><a href="{% url 'soul:vetConsultation' %}">Vet Consultation</a></li>
				            </ul>
				          </li>
				          <li><a href="{% url 'soul:contacts' %}"
						  		style="color: white; font-size: 15px">
							  <i class="far fa-address-card"></i>
							  Contact Us
						  	</a>
						  </li>
							<li><a href="{% url 'soul:changePassword' %}"
									style="color: white; font-size: 15px">
								<i class="fas fa-unlock-alt"></i>
								Change Password</a>
							</li>

                            <li>
								<a href="{% url 'soul:logout' %}"
								style="color: white; font-size: 15px">
									<i class="fas fa-sign-out-alt"></i>
									LogOut
								</a>
							</li>
				        </ul>
				      </nav>
			    	</div>
			    </div>
			  </header><!-- #header -->

                    <center><div class="container" style="margin-top: 150px;">
                        <h2>Your Information</h2>
						<h6>Make it easier to adopt a pet for you.</h6>
                    </div></center>

                <div class="container" style="margin-top: 10px">
                <form name="myform" id="myForm" method="POST" action="{% url 'soul:petfinderform' %}">
                    {% csrf_token %}
                    <div class="container">
                        <label for="firstname"><b>First Name</b></label>
                        <input type="text" placeholder="Enter First Name" name="firstname" id="firstname" required>

                        <label for="lastname"><b>Last Name</b></label>
                        <input type="text" placeholder="Enter Last Name" name="lastname" id="lastname" required>

                        <label for="Address"><b>Address</b></label>
                        <input type="text" placeholder="Enter Address" name="address" id="address" required>

                        <label for="Country"><b>Country</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                         &nbsp;&nbsp;<label for="state"><b>state</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <label for="City"><b>City</b></label><br>
                        <select id="country" size="1" name="country">
                            <option value="" selected="selected">select country</option>
                        </select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


                        <select id="state" size="1" name="state">
                            <option value="" selected="selected">select state</option>
                        </select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


                        <select id="city" size="1" name="city">
                            <option value="" selected="selected">select city</option>
                        </select><br>

                        <label for="email"><b>Email Id</b></label>
                        <input type="email" placeholder="Enter Email" name="email" id="email" required>

                        <label for="text"><b>Phone Number</b></label>
                        <input type="text" placeholder="Enter Phone Number" name="phone" id="phone"
							   pattern="^\d{10}$" title="10 digit number required" required>

                        <!--label for="text"><b>Description</b></label>
                        <textarea placeholder="Enter description of things you want to donate"
                                  name="message" id="message" type="text" required></textarea-->

                        <button type="submit" href="{% url 'soul:petfinderform' %}">Send Request</button>
                    </div>
                </form>
            </div><br><br><br>

                         <!-- start footer Area -->
			<footer class="footer-area" >
				<div class="container">
					<div class="row pt-120 pb-80">
						<div class="col-lg-4 col-md-6">
							<div class="single-footer-widget">
								<h6>About Us</h6>
								<p style="color: white; text-align: justify;">
                                    Our social network has one mission, to help shelter animals get adopted
                                    and find a loving home. Users or animal care facilities can create profiles
                                    of shelter pets with photos, videos and detailed descriptions.
                                    That's why we believe in motto FEEL TOGETHER, HEEL TOGETHER.
                                </p>
							</div>
						</div>
						<div class="col-lg-4 col-md-6">
							<div class="single-footer-widget">
								<h6>Useful Links</h6>
								<div class="row">
									<ul class="col footer-nav">
										<li><a href="{% url 'soul:homepage' %}">Home</a></li>
										<li><a href="{% url 'soul:ngoConsultation' %}">NGO Cunsultation</a></li>
										<li><a href="{% url 'soul:vetConsultation' %}">Vets Consultation</a></li>

									</ul>
									<ul class="col footer-nav">
                                        <li><a href="{% url 'soul:donate' %}">Donate Things</a></li>
										<li><a href="{% url 'soul:contacts' %}">Contact Us</a></li>


									</ul>
								</div>
							</div>
						</div>
						<div class="col-lg-4  col-md-6">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">Contact Us</h6>
								<ul class="list-contact">
									<li class="flex-row d-flex">
										<div class="icon">
											<span class="lnr lnr-home"></span>
										</div>
										<div class="detail">
											<h4>CDAC NETCOM, India</h4>
											<h4>
												globe circle,sitapura
											</h4>
										</div>
									</li><br>
									<li class="flex-row d-flex">
										<div class="icon">
											<span class="lnr lnr-phone-handset"></span>
										</div>
										<div class="detail">
											<h4>91 89675 23456</h4>
											<h4>
												Mon to Fri 9am to 6 pm
											</h4>
										</div>
									</li><br>
									<li class="flex-row d-flex">
										<div class="icon">
											<span class="lnr lnr-envelope"></span>
										</div>
										<div class="detail">
											<h4>rescuethesoul@gmail.com</h4>
											<h4>
												Send us your query anytime!
											</h4>
										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="copyright-text">
					<div class="container" style="text-align: center">
						<div class="row footer-bottom d-flex justify-content-between">
							<p class="col-lg-8 col-sm-6 footer-text m-0 text-white"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script>
								All rights reserved |<i class="fas fa-heart" aria-hidden="true"></i>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
							<div class="col-lg-4 col-sm-6 footer-social">
								<a href="#"><i class="fab fa-facebook-f"></i></a>
								<a href="#"><i class="fab fa-twitter"></i></a>
								<a href="#"><i class="fab fa-instagram"></i></a>
								<a href="#"><i class="fab fa-whatsapp"></i></a>
							</div>
						</div>
					</div>
				</div>
			</footer>
			<!-- End footer Area -->


<script type="text/javascript">
                var stateObject = {
                                   "India": { "Delhi": ["new Delhi", "North Delhi"],
"Kerala": ["Thiruvananthapuram", "Palakkad"],
"Goa": ["North Goa", "South Goa"],
},
"Australia": {
"South Australia": ["Dunstan", "Mitchell"],
"Victoria": ["Altona", "Euroa"]
}, "Canada": {
"Alberta": ["Acadia", "Bighorn"],
"Columbia": ["Washington", ""]
},
                                }
                                window.onload = function () {
                                var country = document.getElementById("country"),
                                state = document.getElementById("state"),
                                city = document.getElementById("city");
for (var count in stateObject) {
country.options[country.options.length] = new Option(count, count);
}
country.onchange = function () {
state.length = 1; // remove all options bar first
city.length = 1; // remove all options bar first
if (this.selectedIndex < 1) return; // done
for (var st in stateObject[this.value]) {
state.options[state.options.length] = new Option(st, st);
}
}
country.onchange(); // reset in case page is reloaded
state.onchange = function () {
city.length = 1; // remove all options bar first
if (this.selectedIndex < 1) return; // done
var cit = stateObject[country.value][this.value];
for (var i = 0; i < cit.length; i++) {
city.options[city.options.length] = new Option(cit[i], cit[i]);
}
}
}

       /* function noBack()
         {
             window.history.forward();
         }
        noBack();
        window.onload = noBack;
        window.onpageshow = function(evt) { if (evt.persisted) noBack() }
        window.onunload = function() { void (0) }*/
    </script>

</body>

</html>

rescue_soul/soul/templates/f.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FAIL</title>
</head>
<body>
    <h2>Not Successful</h2>
</body>
</html>

rescue_soul/soul/templates/fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fail</title>
</head>
<body onload="test()">
    {% if not change_success %}
        <script>
            function test()
            {
                alert("Entered current password is incorrect");
                window.location.assign("http://127.0.0.1:8000/changePassword/")
            }
        </script>

    {% endif %}
</body>
</html>

rescue_soul/soul/templates/portfolio.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->

	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="username">

					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="#">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

rescue_soul/soul/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body onload="test()">
    {% if change_success %}
        <script>
            function test()
            {
                alert("Password changed successfully");
                window.location.assign("http://127.0.0.1:8000/changePassword/")
            }
        </script>

    {% endif %}
</body>
</html>